apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ndyr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ndyr
    app.kubernetes.io/part-of: integ-app-esib
  name: hacbs-test-project-ndyr
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ndyr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ndyr
    spec:
      containers:
      - image: quay.io/kasem_org/integration1-kxor-tenant/integ-app-esib/hacbs-test-project-ndyr@sha256:39d398d9bce8dfb7aee0dcd19ea2ebc2364a7139478ce7ac8df3f7d376c540e5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
